### ISSUE TITLE
process_server_reader parse json_val error cause panic

### ISSUE THREAD

**Issue by tickscn** [blahgeek/emacs-lsp-booster#10]
I added an info log, 
![image](https://github.com/blahgeek/emacs-lsp-booster/assets/28886445/49c24597-0323-475f-b965-b44721b38bf6)
and here is the output of this log.
![image](https://github.com/blahgeek/emacs-lsp-booster/assets/28886445/846ee716-99f6-40af-81ba-50c2e7d2ebe9)

It seems that the bytecode is being read.

**Comment by blahgeek** [comment]
This function reads messages from the lsp server and try to parse it as json. The messages coming from the lsp server cannot possibly be bytecode content.

The most likely scenario I can guess is that this wrapper is used *twice*, aka, `emacs-lsp-wrapper emacs-lsp-wrapper lsp-server args...` is being executed, instead of `emacs-lsp-wrapper lsp-server args...`

I think you should recheck your elisp code. For example, maybe the advice for `lsp-resolve-final-command` is added twice.

**Comment by tickscn** [comment]
Yes, the reason for this problem is that the wrapper is used twice. I have solved it.

**Comment by tickscn** [comment]
Yes, the reason for this problem is that the wrapper is used twice. I have solved it.
